config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses do
    resources :lessons
  end

  resources :lessons do
    resources :sections
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course, optional: true
  has_many :lessons

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :lesson, optional: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
    render :index
  end
  def show
    @course = Course.find(params[:id])
    render :show
  end
end

app/controllers/lessons_controler.rb
class LessonsController < ApplicationController
  def index
    @course = Course.all
    @lesson = @course.lessons
    render :index
  end

  def show
    @course = Course.find(params[:course_id])
    @lesson = @course.lessons
    render :show
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="container">
  <h1>Courses</h1>
  <ul>
    <% @courses.each do |course| %>
    <li><%= link_to course.title, course_path(course) %></li>
    <% end %>
  </ul>

</div>

app/views/courses/show.html.erb
<p> <%= link_to "Courses", courses_path %> </p>

<h4>Lessons for <%= @course.title %></h4>
<% if @course.lessons.any? %>
  <ul>
    <% @course.lessons.each do |lesson| %>
      <li><%= link_to lesson.name, course_lesson_path(@course, lesson) %></li>
      <% end %>
  </ul>
  <% else %>
    <p>There are no </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EpicodusClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/courses">Courses</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>

app/views/lessons/show.html.erb
<h4>sections for <%= @lesson.title %></h4>